# How to insert and deleete data in data frame
# syntax
variable.insert(location,"name",[value])

In [2]:
import pandas as pd

In [3]:
data = {"a":[1,2,3,4],"b":[4,3,2,2]}
dataframe = pd.DataFrame(data)
dataframe
# coloumns c are inserted 
dataframe.insert(2,"c",[9,8,7,6])
dataframe
# columns d are inserted
dataframe.insert(3,"d",["a","s","d","f"])
dataframe

   a  b  c  d
0  1  4  9  a
1  2  3  8  s
2  3  2  7  d
3  4  2  6  f

# coying data from one columns to another

In [4]:
# copying all the elements of column a to e
dataframe["e"] = dataframe["a"][:]
# copying elements from column b to columns f from index o to 3 but three are exclusive
dataframe["f"] = dataframe["b"][:3]
dataframe

   a  b  c  d  e    f
0  1  4  9  a  1  4.0
1  2  3  8  s  2  3.0
2  3  2  7  d  3  2.0
3  4  2  6  f  4  NaN

# deleting data from dataframe

In [5]:
del dataframe["a"]
dataframe.pop("f")
dataframe

   b  c  d  e
0  4  9  a  1
1  3  8  s  2
2  2  7  d  3
3  2  6  f  4

# how to create a csv file from a data frame
csv format is a plain text format in which values are separated by a commas(commas separated values)
<br>
xls file format is an excel sheets binary file format which holds information about all the worksheets in a file ,including both content and formatting

In [ ]:
dic = {"a":[1,2,3,4,5],"b":[5,4,3,2,1],"c":[4,5,6,7,8]}
dt = pd.DataFrame(dic)
dt
dt.to_csv("dummy.csv")
# dt.to_cssv("dummy.csv",index=False) it hide index 
# dt.to_cssv("dummy.csv",index=False,header=[1,2,3]) it remove the old header and replaced with new header