## Medium Level Pandas Problem — Handling Missing Data

You are given sales data with missing values.

In [2]:
import pandas as pd
import numpy as np

In [22]:


data = {
    "Product": ["Laptop", "Mouse", "Keyboard", "Monitor", "Printer"],
    "Price": [80000, np.nan, 3000, 25000, np.nan],
    "Quantity": [5, 10, np.nan, 3, 8],
    "Rating": [4.5, np.nan, 4.2, 4.8, np.nan]
}

df = pd.DataFrame(data)
print(df)
print("\n\n")

# Find total missing values in each column
print(df.isnull().sum())
print("\n\n")
# Fill missing Price values with the mean price
average = df["Price"].mean()
df["Price"] = df["Price"].fillna(average)
print("\n\n\n")
# Fill missing Quantity using forward fill
df["Quantity"] = df["Quantity"].ffill()
#  Fill Rating NaN with 0
df["Rating"] = df["Rating"].fillna(0)
# Create a new column called "Total_Value"
df["total_value"] = df["Price"] * df["Quantity"]
print(df)
# . Find:
# Product with highest total value 
# #Average rating
# Total quantity sold
df.loc[df["Product"].idxmax()]
df["Rating"] = df["Rating"].mean()
df["Quantity"] = df["Quantity"].sum()
df

    Product    Price  Quantity  Rating
0    Laptop  80000.0       5.0     4.5
1     Mouse      NaN      10.0     NaN
2  Keyboard   3000.0       NaN     4.2
3   Monitor  25000.0       3.0     4.8
4   Printer      NaN       8.0     NaN



Product     0
Price       2
Quantity    1
Rating      2
dtype: int64







    Product    Price  Quantity  Rating  total_value
0    Laptop  80000.0       5.0     4.5     400000.0
1     Mouse  36000.0      10.0     0.0     360000.0
2  Keyboard   3000.0      10.0     4.2      30000.0
3   Monitor  25000.0       3.0     4.8      75000.0
4   Printer  36000.0       8.0     0.0     288000.0

    Product    Price  Quantity  Rating  total_value
0    Laptop  80000.0      36.0     2.7     400000.0
1     Mouse  36000.0      36.0     2.7     360000.0
2  Keyboard   3000.0      36.0     2.7      30000.0
3   Monitor  25000.0      36.0     2.7      75000.0
4   Printer  36000.0      36.0     2.7     288000.0

In [23]:
csv_2 = pd.read_csv("/home/jawad/Downloads/people-100.csv")
df = pd.DataFrame(csv_2)
# Display the first 5 rows.
print(df.head(5))
print("\n\n\n")
# Show the total number of missing values per column (count of NaN/None after standardizing missing representations).
print((df.isnull().sum()/len(df) * 100).round(2))
df

   Index          User Id First Name Last Name     Sex  \
0      1  88F7B33d2bcf9f5     Shelby   Terrell    Male
1      2  f90cD3E76f1A9b9    Phillip   Summers  Female
2      3  DbeAb8CcdfeFC2c   Kristine    Travis    Male
3      4  A31Bee3c201ef58    Yesenia  Martinez    Male
4      5  1bA7A3dc874da3c       Lori      Todd    Male

                        Email                   Phone Date of birth  \
0        elijah57@example.net  001-084-906-7849x73518    1945-10-26
1       bethany14@example.com       214.112.6044x4913    1910-03-24
2       bthompson@example.com            277.609.7938    1992-07-02
3   kaitlinkaiser@example.com            584.094.6111    2017-08-03
4  buchananmanuel@example.net       689-207-3558x7233           NaN

            Job Title
0     Games developer
1      Phytotherapist
2           Homeopath
3   Market researcher
4  Veterinary surgeon




Index            0.0
User Id          0.0
First Name       0.0
Last Name        1.0
Sex              3.0
Email            4.0
Phone            1.0
Date of birth    3.0
Job Title        3.0
dtype: float64

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,88F7B33d2bcf9f5,Shelby,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,1945-10-26,Games developer
1,2,f90cD3E76f1A9b9,Phillip,Summers,Female,bethany14@example.com,214.112.6044x4913,1910-03-24,Phytotherapist
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,Male,bthompson@example.com,277.609.7938,1992-07-02,Homeopath
3,4,A31Bee3c201ef58,Yesenia,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,2017-08-03,Market researcher
4,5,1bA7A3dc874da3c,Lori,Todd,Male,buchananmanuel@example.net,689-207-3558x7233,NaN,Veterinary surgeon
...,...,...,...,...,...,...,...,...,...
95,96,5eFda7caAeB260E,Dennis,Barnes,Female,latasha46@example.net,001-865-478-5157,1954-07-30,Software engineer
96,97,CCbFce93d3720bE,Steve,Patterson,Female,regina11@example.org,995-542-3004x76800,1932-04-29,Barrister
97,98,2fEc528aFAF0b69,Wesley,Bray,NaN,alexiscantrell@example.org,001-273-685-6932x092,1994-12-28,Police officer
98,99,Adc7ad9B6e4A1Fe,Summer,Oconnell,Female,pcopeland@example.org,(341)594-6554x44657,2012-04-12,Broadcast journalist
99,100,b8D0aD3490FC7e1,Mariah,Bernard,Male,NaN,NaN,2016-11-15,IT sales professional